#!/usr/bin/python
# convert fodf file into text file

import sys
import re
from HTMLParser import HTMLParser

# http://stackoverflow.com/a/925630
class MLStripper(HTMLParser):
    def __init__(self):
        self.reset()
        self.fed = []
    def handle_data(self, d):
        self.fed.append(d)
    def get_data(self):
        return ''.join(self.fed)

def strip_tags(html):
    s = MLStripper()
    s.feed(html)
    return s.get_data()

def replace_things(text):
    #text.replace('<text:line-break/>', "LINEBREAK")
    text.replace('Grivat', "GRIVAT MEK")
    return text

def main():

    lines = []
    for line in sys.stdin:
        #line = replace_things(line)
        line.replace('Grivat', "GRIVAT MEK")
        lines.append(line)

    text = strip_tags("\n".join(lines))

    for line in text.split("\n"):
        line = line.rstrip()
        if line != '':
            print line



if __name__ == '__main__':
    main()
