#!/usr/bin/python
# Does almost like grep

import sys
import re

def grep(pattern, data):
    p = re.compile(pattern)
    values = []
    for line in data:
        if p.search(line):
            values.append(line)
    return values

# test arguments
files = []
if len(sys.argv) == 2:
    pass
elif len(sys.argv) > 2:
    files = sys.argv[2:]
else:
    sys.stderr.write("Usage: " + sys.argv[0] + " PATTERN [FILE]\n")
    sys.exit(1)

# determine the pattern
pattern = sys.argv[1]

# get the values with the home made grep
values = []
if not files:
    values += grep(pattern, sys.stdin)
else:
    for filename in files:
        with open(filename) as f:
            values += grep(pattern, f.readlines())

# print results

for value in values:
    print value,

# exit

if len(values):
    sys.exit(0)
sys.exit(1)

